// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nodus-landing-a/SentinelGrid.tsx": () => import("../components/mockups/nodus-landing-a/SentinelGrid.tsx"),
  "./components/mockups/nodus-landing-b/EditorialMono.tsx": () => import("../components/mockups/nodus-landing-b/EditorialMono.tsx")
};
